In [3]:
'''pip install numpy'''

'pip install numpy'

In [7]:
import numpy as np

In [5]:
n1 = np.array([1,2,3,4])
print(n1, type(n1))

[1 2 3 4] <class 'numpy.ndarray'>


In [6]:
n1

array([1, 2, 3, 4])

In [8]:
x = []
len(dir(x))

47

In [10]:
len(dir(n1))

165

In [11]:
n1.shape

(4,)

In [13]:
n2 = np.array([[1,2,3],[2,3,5]])
print(n2)
print(n2.shape)

[[1 2 3]
 [2 3 5]]
(2, 3)


creating matrix
- arrange
- linspace
- random.rand
- random.randn
- random.randint
- eye
- ones
- zeros

In [16]:
x=np.arange(-10,10,.2)
x.shape

(100,)

In [19]:
y = np.linspace(1,5,25)
print(y)
y.shape

[1.         1.16666667 1.33333333 1.5        1.66666667 1.83333333
 2.         2.16666667 2.33333333 2.5        2.66666667 2.83333333
 3.         3.16666667 3.33333333 3.5        3.66666667 3.83333333
 4.         4.16666667 4.33333333 4.5        4.66666667 4.83333333
 5.        ]


(25,)

In [22]:
np.random.rand(3,3)

array([[0.71317608, 0.47617082, 0.57868026],
       [0.61667612, 0.68366796, 0.30737478],
       [0.72153676, 0.43676391, 0.46965823]])

In [25]:
np.random.randn(10)

array([ 0.76803021,  0.22909148,  0.14137045,  1.91969161,  1.02774145,
       -1.17452811, -0.54593527,  1.48785725,  2.86721795,  0.37353358])

In [28]:
np.random.randint(1,1000, (5,5))

array([[816, 947, 886, 337,  30],
       [ 53, 711, 825, 868, 641],
       [144, 506, 290,  59, 768],
       [149, 777, 524, 645, 847],
       [405, 588, 896, 290, 444]])

In [29]:
np.random.randint(1,5)

2

In [10]:
x = np.random.randint(1,10, (3,2))
y = np.random.randint(1,10, (3,2))
print(x)
print(y)

[[4 8]
 [7 6]
 [5 8]]
[[1 3]
 [4 6]
 [7 3]]


In [32]:
x + 5

array([[ 6, 11],
       [12,  6],
       [11, 11]])

In [33]:
x + y

array([[10, 11],
       [12, 10],
       [10, 12]])

In [34]:
x / y

array([[0.11111111, 1.2       ],
       [1.4       , 0.11111111],
       [1.5       , 1.        ]])

In [35]:
x * y

array([[ 9, 30],
       [35,  9],
       [24, 36]])

In [43]:
np.sin(x)

array([[ 0.84147098, -0.2794155 ],
       [ 0.6569866 ,  0.84147098],
       [-0.2794155 , -0.2794155 ]])

In [44]:
print(x.sum())
print(x.mean())
print(x.std())

27
4.5
2.5


In [11]:
#dot operation
x.dot(y.T)

array([[28, 64, 52],
       [25, 64, 67],
       [29, 68, 59]])

In [12]:
a = np.linspace(0,5,50)
print(a.shape)
a2 = a.reshape(10,5)
print(a2)
print(a2.shape)

(50,)
[[0.         0.10204082 0.20408163 0.30612245 0.40816327]
 [0.51020408 0.6122449  0.71428571 0.81632653 0.91836735]
 [1.02040816 1.12244898 1.2244898  1.32653061 1.42857143]
 [1.53061224 1.63265306 1.73469388 1.83673469 1.93877551]
 [2.04081633 2.14285714 2.24489796 2.34693878 2.44897959]
 [2.55102041 2.65306122 2.75510204 2.85714286 2.95918367]
 [3.06122449 3.16326531 3.26530612 3.36734694 3.46938776]
 [3.57142857 3.67346939 3.7755102  3.87755102 3.97959184]
 [4.08163265 4.18367347 4.28571429 4.3877551  4.48979592]
 [4.59183673 4.69387755 4.79591837 4.89795918 5.        ]]
(10, 5)


In [22]:
m = np.random.randint(1, 10, (10,10))
print(a)

[[7 9 5 2 4 5 7 6 4 5]
 [1 5 4 4 1 6 2 8 6 4]
 [8 2 4 4 2 2 4 9 4 8]
 [3 6 9 2 1 1 9 4 2 5]
 [1 1 7 6 2 9 6 4 1 7]
 [1 4 8 6 2 7 8 2 3 5]
 [1 6 8 1 4 4 2 8 6 4]
 [7 4 9 6 3 1 3 1 7 5]
 [6 5 3 7 9 8 1 2 5 9]
 [4 4 8 4 1 2 1 6 3 2]]


In [26]:
print(m[0, 0])
print(m[0, -1])
print(m[-1, 0])
print(m[-1, -1])

1
7
5
3
10


In [31]:
print(m[0])
print(m[1])
print(m[-1])

[1 1 7 4 3 2 6 1 5 7]
[6 3 5 5 6 1 7 6 1 1]
[5 4 8 6 5 3 4 3 9 3]


In [28]:
print(m[:3])

[[1 1 7 4 3 2 6 1 5 7]
 [6 3 5 5 6 1 7 6 1 1]
 [6 1 8 4 8 8 8 9 7 2]]


In [29]:
print(m[-3:])

[[6 6 9 5 1 9 6 5 1 7]
 [5 5 7 2 3 9 9 1 6 1]
 [5 4 8 6 5 3 4 3 9 3]]


In [37]:
print(m[:,0])
print(m[:,-1])
print(m[:,:3])
print(m[:,-3:])

[1 6 6 4 6 6 4 6 5 5]
[7 1 2 6 2 4 4 7 1 3]
[[1 1 7]
 [6 3 5]
 [6 1 8]
 [4 3 8]
 [6 8 7]
 [6 6 3]
 [4 3 1]
 [6 6 9]
 [5 5 7]
 [5 4 8]]
[[1 5 7]
 [6 1 1]
 [9 7 2]
 [5 8 6]
 [9 5 2]
 [8 9 4]
 [8 9 4]
 [5 1 7]
 [1 6 1]
 [3 9 3]]


In [38]:
print(m[:, [0,1,3,6]])

[[1 1 4 6]
 [6 3 5 7]
 [6 1 4 8]
 [4 3 7 7]
 [6 8 1 5]
 [6 6 9 3]
 [4 3 9 8]
 [6 6 5 6]
 [5 5 2 9]
 [5 4 6 4]]


filtering

In [41]:
m < 5 #boolean filter

array([[ True,  True, False,  True,  True,  True, False,  True, False,
        False],
       [False,  True, False, False, False,  True, False, False,  True,
         True],
       [False,  True, False,  True, False, False, False, False, False,
         True],
       [ True,  True, False, False,  True,  True, False, False, False,
        False],
       [False, False, False,  True,  True,  True, False, False, False,
         True],
       [False, False,  True, False, False, False,  True, False, False,
         True],
       [ True,  True,  True, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False,  True,
        False],
       [False, False, False,  True,  True, False, False,  True, False,
         True],
       [False,  True, False, False, False,  True,  True,  True, False,
         True]])

In [51]:
m[m<5]
m[m<5].sum()

91

In [48]:
m[(m>3) & (m<=6)]

array([4, 6, 5, 6, 5, 5, 6, 6, 6, 4, 4, 5, 6, 6, 5, 5, 6, 6, 5, 4, 4, 6,
       4, 6, 6, 5, 6, 5, 5, 5, 6, 5, 4, 6, 5, 4])